name: Build Docker image (CI)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ linux/amd64, linux/arm64 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      # Derive a slash-free arch string and prepare output dir
      - name: Derive ARCH and prepare out dir
        id: vars
        shell: bash
        run: |
          ARCH="${{ matrix.platform }}"   # "linux/amd64" -> "amd64"
          echo "ARCH=$ARCH" >> "$GITHUB_OUTPUT"
          mkdir -p /tmp/out

      # Generate VALID tags (no slashes) using metadata-action
      - name: Docker metadata (tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: serenityjs
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.vars.outputs.ARCH }}

      # Optional: sanity check to fail fast if any tag has a slash
      - name: Check tags contain no slashes
        shell: bash
        run: |
          echo "Tags:"
          echo "${{ steps.meta.outputs.tags }}"
          if echo "${{ steps.meta.outputs.tags }}" | grep -q '/'; then
            echo "ERROR: A tag contains '/'."
            exit 1
          fi

      - name: Build image → tar (single-platform)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}     # OK to use full platform here
          push: false
          # Use the tags computed above (latest + amd64/arm64)
          tags: ${{ steps.meta.outputs.tags }}
          # Export to a fixed, safe file (no slashes)
          outputs: type=docker,dest=/tmp/out/serenityjs-${{ steps.vars.outputs.ARCH }}.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify output
        run: ls -l /tmp/out

      - name: Upload image tar
        uses: actions/upload-artifact@v4
        with:
          name: serenityjs-image-${{ steps.vars.outputs.ARCH }}
          path: /tmp/out/serenityjs-${{ steps.vars.outputs.ARCH }}.tar
          compression-level: 0
          retention-days: 7
