name: Build Docker image (CI)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ linux/amd64, linux/arm64 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Derive ARCH and prepare out dir
        id: vars
        shell: bash
        run: |
          # matrix.platform looks like "linux/amd64" or "linux/arm64"
          ARCH="${{ matrix.platform }}"     # -> amd64 or arm64
          echo "ARCH=$ARCH" >> "$GITHUB_OUTPUT"
          mkdir -p /tmp/out

      - name: Build image → tar (single-platform)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}   # keep full platform here (OK)
          push: false
          # ✅ VALID tags (no slashes in the tag part)
          tags: |
            serenityjs:latest
            serenityjs:${{ steps.vars.outputs.ARCH }}
          # ✅ VALID output path (no slashes from platform)
          outputs: type=docker,dest=/tmp/out/serenityjs-${{ steps.vars.outputs.ARCH }}.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify tar exists
        run: ls -l /tmp/out

      - name: Upload image tar
        uses: actions/upload-artifact@v4
        with:
          name: serenityjs-image-${{ steps.vars.outputs.ARCH }}
          path: /tmp/out/serenityjs-${{ steps.vars.outputs.ARCH }}.tar
          compression-level: 0
          retention-days: 7
