name: Build Docker image (CI)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ linux/amd64, linux/arm64 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Derive ARCH and prepare out dir
        id: vars
        shell: bash
        run: |
          # matrix.platform is like "linux/amd64" → take the part after the slash
          ARCH="${{ matrix.platform }}"             # -> amd64 or arm64
          echo "ARCH=$ARCH" >> "$GITHUB_OUTPUT"
          OUT_TAR="/tmp/out/serenityjs-$ARCH.tar"
          echo "OUT_TAR=$OUT_TAR" >> "$GITHUB_OUTPUT"
          mkdir -p /tmp/out

      - name: Build image → temp tar (single-platform)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}   # full platform is fine here
          push: false
          # Clean tags (NO slashes)
          tags: |
            serenityjs
            serenityjs:${{ steps.vars.outputs.ARCH }}
          # Export to a SAFE, constant file (avoid slashes in path)
          outputs: type=docker,dest=/tmp/image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Move tar to arch-specific name
        shell: bash
        run: mv /tmp/image.tar "${{ steps.vars.outputs.OUT_TAR }}"

      - name: Verify output
        run: ls -l /tmp/out

      - name: Upload image tar
        uses: actions/upload-artifact@v4
        with:
          name: serenityjs-image-${{ steps.vars.outputs.ARCH }}
          path: ${{ steps.vars.outputs.OUT_TAR }}
          compression-level: 0
          retention-days: 7
